export default function Features() {
  return (
    <section className="bg-white dark:bg-gray-900">
      <div className="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
        <div className="max-w-screen-md mb-8 lg:mb-16">
          <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Project Features</h2>
          <p className="text-gray-500 sm:text-xl dark:text-gray-400">Explore the powerful features that make NutriAI a state-of-the-art nutrition planning tool.</p>
        </div>
        <div className="space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-12 md:space-y-0">
          <div>
            <div className="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-green-100 lg:h-12 lg:w-12 dark:bg-green-900">
              {/* Icon */}
            </div>
            <h3 className="mb-2 text-xl font-bold dark:text-white">AI Recommendations</h3>
            <p className="text-gray-500 dark:text-gray-400">Personalized meal plans generated by a sophisticated AI engine.</p>
          </div>
          <div>
            <div className="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-green-100 lg:h-12 lg:w-12 dark:bg-green-900">
              {/* Icon */}
            </div>
            <h3 className="mb-2 text-xl font-bold dark:text-white">Health Profile Management</h3>
            <p className="text-gray-500 dark:text-gray-400">Track and manage your health metrics, goals, and preferences.</p>
          </div>
          <div>
            <div className="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-green-100 lg:h-12 lg:w-12 dark:bg-green-900">
              {/* Icon */}
            </div>
            <h3 className="mb-2 text-xl font-bold dark:text-white">Interactive Dashboard</h3>
            <p className="text-gray-500 dark:text-gray-400">Visualize your progress with an intuitive and responsive dashboard.</p>
          </div>
          <div>
            <div className="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-green-100 lg:h-12 lg:w-12 dark:bg-green-900">
              {/* Icon */}
            </div>
            <h3 className="mb-2 text-xl font-bold dark:text-white">Analytics & Insights</h3>
            <p className="text-gray-500 dark:text-gray-400">Gain deep insights into your nutritional habits with our analytics module.</p>
          </div>
          <div>
            <div className="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-green-100 lg:h-12 lg:w-12 dark:bg-green-900">
              {/* Icon */}
            </div>
            <h3 className="mb-2 text-xl font-bold dark:text-white">Power BI Integration</h3>
            <p className="text-gray-500 dark:text-gray-400">Seamless integration with Power BI for advanced data visualization.</p>
          </div>
          <div>
            <div className="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-green-100 lg:h-12 lg:w-12 dark:bg-green-900">
              {/* Icon */}
            </div>
            <h3 className="mb-2 text-xl font-bold dark:text-white">Admin Panel</h3>
            <p className="text-gray-500 dark:text-gray-400">A comprehensive admin panel to manage users, food data, and recommendations.</p>
          </div>
        </div>
      </div>
    </section>
  );
}
